// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "src/shared/infra/db/prisma/schema",
  migrations: {
    path: "src/shared/infra/db/prisma/migrations",
    seed: "ts-node src/shared/infra/db/prisma/seeders/index.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
